/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ConfigurazioneCollocamentoMirato } from '../model/configurazioneCollocamentoMirato';
import { ConfigurazioneFamiliariACarico } from '../model/configurazioneFamiliariACarico';
import { DatiInputSaveRichiestaIscrizioneCollocamentoMirato } from '../model/datiInputSaveRichiestaIscrizioneCollocamentoMirato';
import { DettaglioCompletoDichiarazioneFamiliariACarico } from '../model/dettaglioCompletoDichiarazioneFamiliariACarico';
import { ErrorDef } from '../model/errorDef';
import { EsitoRicercaRichiestaIscrizioneCollocamentoMirato } from '../model/esitoRicercaRichiestaIscrizioneCollocamentoMirato';
import { EsitoRiepilogoCollocamentoMirato } from '../model/esitoRiepilogoCollocamentoMirato';
import { EsitoSalvataggioRedditoCollocamentoMirato } from '../model/esitoSalvataggioRedditoCollocamentoMirato';
import { EsitoSaveDichiarazione } from '../model/esitoSaveDichiarazione';
import { EsitoSaveRichiestaIscrizioneCollocamentoMirato } from '../model/esitoSaveRichiestaIscrizioneCollocamentoMirato';
import { ParametriSalvataggioRedditoCollocamentoMirato } from '../model/parametriSalvataggioRedditoCollocamentoMirato';


import { Configuration }                                     from '../configuration';


export interface CollocamentoMiratoServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * 
    * 
    * @param id_utente 
    * @param id_richiesta 
    */
    findRichiestaIscrizioneCollocamentoMirato(id_utente: number, id_richiesta?: number, extraHttpRequestParams?: any): Observable<EsitoRicercaRichiestaIscrizioneCollocamentoMirato>;

    /**
    * 
    * 
    * @param id_utente 
    */
    getRiepilogoCollocamentoMirato(id_utente: number, extraHttpRequestParams?: any): Observable<EsitoRiepilogoCollocamentoMirato>;

    /**
    * 
    * 
    */
    loadConfigurazioneFamiliariACarico(extraHttpRequestParams?: any): Observable<ConfigurazioneFamiliariACarico>;

    /**
    * 
    * 
    */
    loadConfigurazioniCollocamentoMirato(extraHttpRequestParams?: any): Observable<ConfigurazioneCollocamentoMirato>;

    /**
    * 
    * 
    * @param id_utente 
    * @param messaggio 
    */
    saveFamiliariACarico(id_utente: number, messaggio: DettaglioCompletoDichiarazioneFamiliariACarico, extraHttpRequestParams?: any): Observable<EsitoSaveDichiarazione>;

    /**
    * 
    * 
    * @param id_utente 
    * @param parametriReddito 
    */
    saveRedditoCollocamentoMirato(id_utente: number, parametriReddito: ParametriSalvataggioRedditoCollocamentoMirato, extraHttpRequestParams?: any): Observable<EsitoSalvataggioRedditoCollocamentoMirato>;

    /**
    * 
    * 
    * @param id_utente 
    * @param parametri_richiesta 
    */
    saveRichiestaIscrizioneCollocamentoMirato(id_utente: number, parametri_richiesta: DatiInputSaveRichiestaIscrizioneCollocamentoMirato, extraHttpRequestParams?: any): Observable<EsitoSaveRichiestaIscrizioneCollocamentoMirato>;

}
