/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ConfigurazioneProfilingDid } from '../model/configurazioneProfilingDid';
import { DatiInputAggiornamentoDid } from '../model/datiInputAggiornamentoDid';
import { DatiInputProfilingDid } from '../model/datiInputProfilingDid';
import { ErrorDef } from '../model/errorDef';
import { EsitoDettaglioDid } from '../model/esitoDettaglioDid';
import { EsitoSaveDid } from '../model/esitoSaveDid';
import { EsitoSaveProfilingDid } from '../model/esitoSaveProfilingDid';


import { Configuration }                                     from '../configuration';


export interface DidServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * 
    * 
    * @param id_utente 
    * @param parametri_sendDid 
    */
    changeStateDidAfterInsertProfilingService(id_utente: number, parametri_sendDid: DatiInputAggiornamentoDid, extraHttpRequestParams?: any): Observable<EsitoSaveDid>;

    /**
    * 
    * 
    * @param id_utente 
    * @param scrivere_log_su_db 
    * @param parametri_sendDid 
    */
    controlloDidService(id_utente: number, scrivere_log_su_db: string, parametri_sendDid: DatiInputAggiornamentoDid, extraHttpRequestParams?: any): Observable<EsitoSaveDid>;

    /**
    * 
    * 
    */
    loadConfigurazioneProfilingDid(extraHttpRequestParams?: any): Observable<ConfigurazioneProfilingDid>;

    /**
    * 
    * 
    * @param id_utente 
    * @param msg 
    */
    logService(id_utente: number, msg: string, extraHttpRequestParams?: any): Observable<ErrorDef>;

    /**
    * 
    * 
    * @param id_utente 
    */
    ricercaDettaglioDIDService(id_utente: number, extraHttpRequestParams?: any): Observable<EsitoDettaglioDid>;

    /**
    * 
    * 
    * @param id_utente 
    * @param parametri_sendDid 
    */
    saveDidService(id_utente: number, parametri_sendDid: DatiInputAggiornamentoDid, extraHttpRequestParams?: any): Observable<EsitoSaveDid>;

    /**
    * 
    * 
    * @param id_utente 
    * @param parametri_sendProfilingDid 
    */
    saveProfilingDidService(id_utente: number, parametri_sendProfilingDid: DatiInputProfilingDid, extraHttpRequestParams?: any): Observable<EsitoSaveProfilingDid>;

}
