/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Ambito } from '../model/ambito';
import { ConfigurazioneCalendario } from '../model/configurazioneCalendario';
import { ConfigurazioneCalendarioHeader } from '../model/configurazioneCalendarioHeader';
import { ConfigurazioneInformazioneAggiuntiva } from '../model/configurazioneInformazioneAggiuntiva';
import { ConfigurazioneMessaggiAggiuntivi } from '../model/configurazioneMessaggiAggiuntivi';
import { Ente } from '../model/ente';
import { ErrorDef } from '../model/errorDef';
import { Esito } from '../model/esito';
import { EsitoDuplicazionePeriodo } from '../model/esitoDuplicazionePeriodo';
import { Messaggio } from '../model/messaggio';
import { Operatore } from '../model/operatore';
import { ParametriDatoCalendari } from '../model/parametriDatoCalendari';
import { ParametriDuplicazioneCalendario } from '../model/parametriDuplicazioneCalendario';
import { ParametriDuplicazionePeriodo } from '../model/parametriDuplicazionePeriodo';
import { ParametriEccezioneCalendari } from '../model/parametriEccezioneCalendari';
import { ParametriEliminazioneEccezione } from '../model/parametriEliminazioneEccezione';
import { ParametriEliminazioneFascia } from '../model/parametriEliminazioneFascia';
import { ParametriRicercaCalendari } from '../model/parametriRicercaCalendari';
import { Sportello } from '../model/sportello';


import { Configuration }                                     from '../configuration';


export interface GestoreServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * 
    * 
    * @param id_utente 
    * @param parametriDatoCalendari 
    */
    applicaDatoACalendari(id_utente: number, parametriDatoCalendari: ParametriDatoCalendari, extraHttpRequestParams?: any): Observable<Esito>;

    /**
    * 
    * 
    * @param id_utente 
    * @param parametriEccezioneCalendari 
    */
    applicaEccezioneACalendari(id_utente: number, parametriEccezioneCalendari: ParametriEccezioneCalendari, extraHttpRequestParams?: any): Observable<Esito>;

    /**
    * 
    * 
    * @param id_utente 
    * @param id_calendario identificativo in PSLP_T_CALENDARIO
    * @param parametri_duplicazione_calendario 
    */
    duplicaCalendario(id_utente: number, id_calendario: number, parametri_duplicazione_calendario: ParametriDuplicazioneCalendario, extraHttpRequestParams?: any): Observable<ConfigurazioneCalendario>;

    /**
    * 
    * 
    * @param id_utente 
    * @param parametri_duplicazione_periodo 
    */
    duplicaPeriodo(id_utente: number, parametri_duplicazione_periodo: ParametriDuplicazionePeriodo, extraHttpRequestParams?: any): Observable<EsitoDuplicazionePeriodo>;

    /**
    * 
    * 
    * @param id_utente 
    * @param id_calendario identificativo in PSLP_T_CALENDARIO
    */
    eliminaCalendario(id_utente: number, id_calendario: number, extraHttpRequestParams?: any): Observable<Esito>;

    /**
    * 
    * 
    * @param id_utente 
    * @param parametri_eliminazione_eccezione 
    */
    eliminaEccezione(id_utente: number, parametri_eliminazione_eccezione: ParametriEliminazioneEccezione, extraHttpRequestParams?: any): Observable<Esito>;

    /**
    * 
    * 
    * @param id_utente 
    * @param parametri_eliminazione_fascia 
    */
    eliminaFascia(id_utente: number, parametri_eliminazione_fascia: ParametriEliminazioneFascia, extraHttpRequestParams?: any): Observable<Esito>;

    /**
    * 
    * 
    * @param id_utente 
    * @param parametriRicercaCalendari 
    */
    findCalendari(id_utente: number, parametriRicercaCalendari: ParametriRicercaCalendari, extraHttpRequestParams?: any): Observable<Array<ConfigurazioneCalendarioHeader>>;

    /**
    * 
    * 
    * @param id_utente 
    * @param id_periodo 
    */
    generaSlot(id_utente: number, id_periodo: number, extraHttpRequestParams?: any): Observable<Esito>;

    /**
    * 
    * 
    * @param id_utente 
    */
    getAmbiti(id_utente: number, extraHttpRequestParams?: any): Observable<Array<Ambito>>;

    /**
    * 
    * 
    * @param id_utente 
    * @param cod_tipo_utente tipologia di utente CIT, APL, CPI, REG
    * @param modalita I&#x3D;Inserimento, M&#x3D;Modifica
    */
    getEnti(id_utente: number, cod_tipo_utente: string, modalita: string, extraHttpRequestParams?: any): Observable<Array<Ente>>;

    /**
    * 
    * 
    * @param id_utente 
    */
    getMessaggi(id_utente: number, extraHttpRequestParams?: any): Observable<Array<Messaggio>>;

    /**
    * 
    * 
    * @param codice_fiscale 
    */
    getOperatoreByCf(codice_fiscale: string, extraHttpRequestParams?: any): Observable<Array<Operatore>>;

    /**
    * 
    * 
    * @param id_utente 
    * @param cod_tipo_utente tipologia di utente CIT, APL, CPI, REG
    */
    getSportelli(id_utente: number, cod_tipo_utente: string, extraHttpRequestParams?: any): Observable<Array<Sportello>>;

    /**
    * 
    * 
    * @param id_utente 
    * @param id_calendario identificativo in PSLP_T_CALENDARIO
    * @param flag_blocco_calendario 
    */
    impostaBloccoCalendario(id_utente: number, id_calendario: number, flag_blocco_calendario: boolean, extraHttpRequestParams?: any): Observable<Esito>;

    /**
    * 
    * 
    * @param id_utente 
    * @param id_calendario 
    */
    loadCalendario(id_utente: number, id_calendario: number, extraHttpRequestParams?: any): Observable<ConfigurazioneCalendario>;

    /**
    * 
    * 
    * @param id_utente 
    * @param cod_ambito 
    */
    loadMessaggiAggiuntiviAmbito(id_utente: number, cod_ambito?: string, extraHttpRequestParams?: any): Observable<Array<ConfigurazioneMessaggiAggiuntivi>>;

    /**
    * 
    * 
    * @param id_utente 
    * @param configurazione_calendario 
    */
    saveCalendarioDatiGenerali(id_utente: number, configurazione_calendario: ConfigurazioneCalendario, extraHttpRequestParams?: any): Observable<ConfigurazioneCalendario>;

    /**
    * 
    * 
    * @param id_utente 
    * @param configurazione_calendario 
    */
    saveCalendarioDatiOperativi(id_utente: number, configurazione_calendario: ConfigurazioneCalendario, extraHttpRequestParams?: any): Observable<ConfigurazioneCalendario>;

    /**
    * 
    * 
    * @param id_utente 
    * @param configurazione_calendario 
    */
    saveCalendarioEccezioni(id_utente: number, configurazione_calendario: ConfigurazioneCalendario, extraHttpRequestParams?: any): Observable<ConfigurazioneCalendario>;

    /**
    * 
    * 
    * @param id_utente 
    * @param configurazione_calendario 
    */
    saveCalendarioFasce(id_utente: number, configurazione_calendario: ConfigurazioneCalendario, extraHttpRequestParams?: any): Observable<ConfigurazioneCalendario>;

    /**
    * 
    * 
    * @param id_utente 
    * @param configurazione_calendario 
    */
    saveCalendarioMail(id_utente: number, configurazione_calendario: ConfigurazioneCalendario, extraHttpRequestParams?: any): Observable<ConfigurazioneCalendario>;

    /**
    * 
    * 
    * @param id_utente 
    * @param messaggio 
    */
    saveConfigurazioneInformazioniAggiuntive(id_utente: number, messaggio: ConfigurazioneInformazioneAggiuntiva, extraHttpRequestParams?: any): Observable<ConfigurazioneInformazioneAggiuntiva>;

    /**
    * 
    * 
    * @param id_utente 
    * @param messaggi 
    */
    saveMessaggiAggiuntiviAmbito(id_utente: number, messaggi: ConfigurazioneMessaggiAggiuntivi, extraHttpRequestParams?: any): Observable<Esito>;

    /**
    * 
    * 
    * @param id_utente 
    * @param messaggio 
    */
    saveMessaggio(id_utente: number, messaggio: Messaggio, extraHttpRequestParams?: any): Observable<Messaggio>;

    /**
    * 
    * 
    * @param id_utente 
    * @param id_calendario identificativo in PSLP_T_CALENDARIO
    */
    verificaVincoliEliminazioneCalendario(id_utente: number, id_calendario: number, extraHttpRequestParams?: any): Observable<Esito>;

}
