/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorDef } from '../model/errorDef';
import { MenuItem } from '../model/menuItem';
import { Role } from '../model/role';
import { Screen } from '../model/screen';
import { UserInfo } from '../model/userInfo';
import { Widget } from '../model/widget';


import { Configuration }                                     from '../configuration';


export interface SecurityServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
    * get current user
    * restituisce l&#39;utente corrente
    */
    getCurrentUser(extraHttpRequestParams?: any): Observable<UserInfo>;

    /**
    * 
    * restituisce la struttura di menu (con abilitazioni) per l&#39;utente corrente
    */
    getMenuStructureForUser(extraHttpRequestParams?: any): Observable<Array<MenuItem>>;

    /**
    * 
    * restituisce la struttura dello screen specificato, con le abilitazioni per l&#39;utente collegato
    * @param screen 
    */
    getScreenByCod(screen: string, extraHttpRequestParams?: any): Observable<Screen>;

    /**
    * get current user role list
    * restituisce la lista di ruoli a cui appartiene l&#39;utente corrente
    */
    getUserRoles(extraHttpRequestParams?: any): Observable<Array<Role>>;

    /**
    * 
    * restituisce il widget specificato. E&#39; utile per interrogazioni puntuali
    * @param screen 
    * @param widget 
    */
    getWidget(screen: string, widget: string, extraHttpRequestParams?: any): Observable<Widget>;

    /**
    * l&#39;utente appartiene al ruolo?
    * challenge di appartenenza dell&#39;utente corrente al ruolo specificato
    * @param role 
    */
    isUserInRole(role: string, extraHttpRequestParams?: any): Observable<Role>;

}
