/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AdesioneYG { 
    id_sil_lav_adesione?: number;
    codice?: string;
    data_adesione?: Date;
    codice_fiscale?: string;
    identificativo_sap?: string;
    data_stato_corrente?: Date;
    stato_corrente_finale?: string;
    descrizione?: string;
    regione?: string;
    flg_anpal_stato_corrente?: string;
    motivo_rifiuto_stato_corrente?: string;
    flg_rifiuto_stato_corrente?: string;
    data_rifiuto?: Date;
    presenzaPiuAdesioniAperte?: boolean;
}
