/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CallOptions { 
    /**
     * http status che il servizio dovra sollevare
     */
    desiredStatus?: number;
    /**
     * tempo in millisecondi che il servizio dovra impiegare per l'esecuzione (per testare meccanismi di timeout)
     */
    executionTime?: number;
}
