/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CategoriaProtetta { 
    id_silp?: string;
    descrizione_silp?: string;
    codice_ministero?: string;
    descrizione_ministero?: string;
    flg_speciale?: string;
    data_inizio?: Date;
    data_fine?: Date;
}
