/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CategoriaProtettaDisab { 
    id_silp?: string;
    num_grado_disabilita_min?: number;
    flg_attivare_grado_o_categoria?: string;
    descrizione?: string;
}
