/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CentroPerImpiego { 
    /**
     * codice centro per impiego
     */
    codice?: string;
    /**
     * descrizione
     */
    descrizione?: string;
    /**
     * flg attivo
     */
    flg_attivo?: boolean;
    /**
     * identificativo univoco su silp
     */
    id_cpi_silp?: number;
    /**
     * identificativo univoco su silp della provincia
     */
    codice_ministeriale_provincia?: string;
}
