/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Provincia } from './provincia';


export interface Comune { 
    /**
     * codice ministeriale
     */
    codice_ministeriale?: string;
    /**
     * descrizione
     */
    descrizione?: string;
    /**
     * cap
     */
    cap?: string;
    /**
     * provincia
     */
    provincia?: Provincia;
    /**
     * id cpi silp
     */
    id_cpi_silp?: number;
}
