/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConfigurazioneCalendarioEccezione } from './configurazioneCalendarioEccezione';
import { ConfigurazioneCalendarioFascia } from './configurazioneCalendarioFascia';


export interface ConfigurazioneCalendarioPeriodoValidita { 
    id_periodo?: number;
    data_da?: Date;
    data_a?: Date;
    flag_slot_generati?: boolean;
    fasce?: Array<ConfigurazioneCalendarioFascia>;
    eccezioni?: Array<ConfigurazioneCalendarioEccezione>;
}
