/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConfigurazioneQuestionario } from './configurazioneQuestionario';
import { Decodifica } from './decodifica';
import { GradoStudio } from './gradoStudio';
import { TitoloStudio } from './titoloStudio';


export interface ConfigurazioneProfilingDid { 
    elencoCittadinanza?: Array<Decodifica>;
    elencoPosizioneProfessionale?: Array<Decodifica>;
    elencoIscrizioneCorso?: Array<Decodifica>;
    elencoPresenzaInItalia?: Array<Decodifica>;
    elencoCondizioniOccupazionali?: Array<Decodifica>;
    elencoTitoloStudioProfiling?: Array<TitoloStudio>;
    elencoGradoStudio?: Array<GradoStudio>;
    configurazione_questionario?: ConfigurazioneQuestionario;
}
