/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConfigurazioneRisposta } from './configurazioneRisposta';


export interface ConfigurazioneDomanda { 
    id_configurazione_questionario?: number;
    id_domanda?: number;
    tipo_domanda?: string;
    domanda?: string;
    posizione?: number;
    risposte?: Array<ConfigurazioneRisposta>;
}
