/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoriaProtetta } from './categoriaProtetta';
import { CategoriaProtettaDisab } from './categoriaProtettaDisab';
import { Decodifica } from './decodifica';


export interface ConfigurazioneCollocamentoMirato { 
    elenco_tipo_iscrizione?: Array<Decodifica>;
    elenco_motivo_iscrizione?: Array<Decodifica>;
    elenco_stato_iscrizione?: Array<Decodifica>;
    elenco_tipo_comunicazione?: Array<Decodifica>;
    elenco_categoria_protetta_disabili?: Array<CategoriaProtettaDisab>;
    elenco_categoria_protetta?: Array<CategoriaProtetta>;
    elenco_qualifiche_non_vedenti?: Array<Decodifica>;
    elenco_categoria_invalidita_disabili?: Array<Decodifica>;
    limite_reddito_lordo_annuo_rapporto_autonomo?: number;
    limite_reddito_lordo_annuo_rapporto_subordinato?: number;
    grado_disabilita_non_vedenti?: string;
    grado_disabilita_sordomuti?: string;
    elenco_dichiarazione_visita_revisione_invalidita_civile?: Array<Decodifica>;
}
