/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ConfigurazioneCalendarioMail { 
    flag_invio_mail_conferma_prenotazione?: boolean;
    ore_invio_mail_promemoria_prenotazione?: number;
    oggetto_mail?: string;
    messaggio_aggiuntivo_mail_conferma?: string;
    messaggio_aggiuntivo_mail_promemoria?: string;
    messaggio_aggiuntivo_mail_annullamento?: string;
    messaggio_aggiuntivo_mail_non_presentato?: string;
}
