/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ConfigurazioneInformazioneAggiuntiva { 
    codice?: number;
    codice_ministeriale?: string;
    cod_ambito?: string;
    descrizione?: string;
    bloccante?: string;
    valore?: string;
    flag_visibile_pslp?: string;
    /**
     * data inizio
     */
    data_inizio?: Date;
    /**
     * data fine
     */
    data_fine?: Date;
}
