/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ConfigurazioneCalendarioFascia { 
    id_fascia?: number;
    id_giorno_settimana?: number;
    num_max_prenotazioni?: number;
    ora_inizio?: number;
    ora_fine?: number;
    durata_slot?: number;
}
