/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ConfigurazioneCalendarioHeader { 
    /**
     * identificativo in PSLP_T_CALENDARIO
     */
    id_calendario?: number;
    /**
     * ambito di appartenenza
     */
    descrizione_ambito?: string;
    /**
     * nome del calendario
     */
    nome?: string;
    /**
     * descrizione del cpi di appartenenza del calendario
     */
    descrizione_ente?: string;
    /**
     * sequenza di giorni ddd
     */
    giorni_attivi?: string;
    /**
     * da-a
     */
    periodo?: string;
    visibile_in_base?: string;
    promemoria?: boolean;
    eliminato?: boolean;
    bloccato?: boolean;
    ore_limite_spostamento?: number;
    annulla_garanzia_giovani?: boolean;
    messaggio_annullamento_appuntamento?: string;
    messaggio_spostamento_appuntamento?: string;
    numero_slot_liberi?: number;
    numero_slot_prenotabili?: number;
}
