/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConfigurazioneCalendarioDatiOperativi } from './configurazioneCalendarioDatiOperativi';
import { ConfigurazioneCalendarioMail } from './configurazioneCalendarioMail';
import { ConfigurazioneCalendarioPeriodoValidita } from './configurazioneCalendarioPeriodoValidita';


export interface ConfigurazioneCalendario { 
    /**
     * identificativo univoco
     */
    id_calendario?: number;
    /**
     * nome calendario
     */
    nome?: string;
    /**
     * codice ambito
     */
    codice_ambito?: string;
    gruppo_operatore?: string;
    codice_operatore?: number;
    subcodice?: number;
    dati_operativi?: ConfigurazioneCalendarioDatiOperativi;
    periodi_validita?: Array<ConfigurazioneCalendarioPeriodoValidita>;
    mail?: ConfigurazioneCalendarioMail;
}
