/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Decodifica } from './decodifica';
import { ListaSpeciale } from './listaSpeciale';


export interface DatiAmministrativi { 
    stato_occupazionale?: Decodifica;
    condizione?: Decodifica;
    categoria_dlg297?: Decodifica;
    anzianita_disoccupazione_mesi?: number;
    indice_profiling?: string;
    data_evento?: Date;
    data_dichiarazione_disponibilita?: Date;
    liste_speciali?: Array<ListaSpeciale>;
    obbligo_formativo_assolto?: boolean;
    appartenenza_categorie_protette?: Decodifica;
    indice_isee?: string;
}
