/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DatiInputProfilingDid { 
    id_anagrafica?: number;
    codice_fiscale?: string;
    id_titolo_studio?: string;
    id_condizione_occupazionale?: string;
    id_posizione_professionale?: string;
    id_iscrizione_corsi?: string;
    id_presenza_in_italia?: string;
    avuto_almeno_un_lav?: boolean;
    figli_a_carico?: boolean;
    figli_minori_a_carico?: boolean;
    num_mesi_fine_ultimo_lavoro?: number;
    num_mesi_ricerca_lavoro?: number;
    num_componenti_famiglia?: number;
}
