/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * dati profiling
 */
export interface DatiProfilingDid { 
    eta?: number;
    /**
     * data inserimento
     */
    data_inserimento?: Date;
    /**
     * data did
     */
    data_did?: Date;
    /**
     * data disoccupazione profiling
     */
    data_disoccupazione?: Date;
    flg_figli_carico?: string;
    flg_figli_carico_minori?: string;
    flg_genere?: string;
    flg_ha_avuto_lavoro?: string;
    ds_cittadinanza?: string;
    ds_titolo_studio?: string;
    codice_ministeriale_titolo_studio?: string;
    ds_condizione_occupazionale?: string;
    num_mesi_ultimo_rapporto?: number;
    num_mesi_ricerca_lavoro?: number;
    num_componenti_famiglia?: number;
    ds_iscrizione_corsi?: string;
    ds_provincia_residenza?: string;
    ds_presenza_in_italia?: string;
    ds_posizione_professionale?: string;
    /**
     * numero decimale di lunghezza totale 10 con 9 decimali. Rappresento in stringa per comodita (preso da PoliticaAttiva)
     */
    indice_profiling?: string;
}
