/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Decodifica } from './decodifica';
import { Luogo } from './luogo';


export interface DettaglioDichiarazioneFamiliariACarico { 
    motivo_carico?: Decodifica;
    /**
     * codice fiscale familiare
     */
    codice_fiscale_familiare?: string;
    cognome_familiare?: string;
    nome_familiare?: string;
    data_nascita_familiare?: Date;
    sesso?: string;
    luogo_di_nascita?: Luogo;
    flg_validita_cf?: string;
}
