/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Decodifica } from './decodifica';
import { DettaglioDichiarazioneFamiliariACarico } from './dettaglioDichiarazioneFamiliariACarico';


export interface DettaglioCompletoDichiarazioneFamiliariACarico { 
    id_dichiarazione?: number;
    /**
     * id lavoratore su SILP
     */
    id_sil_lav_anagrafica?: number;
    numero_familiari?: number;
    anno_validita?: number;
    data_dichiarazione?: Date;
    /**
     * true se e' l'ultima dichiarazione inserita
     */
    flag_ultima_dichiarazione_inserita?: boolean;
    /**
     * true se la dichiarazione e' stata duplicata
     */
    flag_duplicazione_dichiarazione?: boolean;
    fonte?: string;
    cpi?: Decodifica;
    data_nascita_dichiarante?: Date;
    note?: string;
    dettaglio_dichiarazione_familiari_a_carico?: Array<DettaglioDichiarazioneFamiliariACarico>;
}
