/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Documento { 
    id?: number;
    id_sil_lav_sap_did?: number;
    codice_tipo_documento?: string;
    codice_estensione?: string;
    codice_operatore?: number;
    codice_utente_inserimento?: string;
    codice_utente_aggiornamento?: string;
    data_inserimento?: Date;
    data_inserim?: Date;
    data_aggiornamento?: Date;
    data_invio?: Date;
    nome?: string;
    ambito?: string;
    pdf?: string;
    subcodice?: number;
    note_operatore?: string;
    id_utente?: number;
    note_cittadino?: string;
    stato?: string;
    gruppo_operatore?: string;
    codice_fiscale_operatore?: string;
    flg_obbligatorio?: string;
    id_sil_rich_coll_mir?: number;
}
