/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Comune } from './comune';
import { Ente } from './ente';


export interface DomandaRDC { 
    id_sil_lav_domanda_rdc?: number;
    codice?: string;
    data_domanda?: Date;
    data_notifica_silp?: Date;
    stato_domanda?: string;
    stato_politica_rc1?: string;
    data_stato_politica_rc1?: Date;
    comune_residenza?: Comune;
    ente_residenza?: Ente;
}
