/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Decodifica } from './decodifica';
import { TipoConoscenzaInformatica } from './tipoConoscenzaInformatica';
import { TipoContratto } from './tipoContratto';


export interface ElenchiDecodifiche { 
    lingue?: Array<Decodifica>;
    gradi_conoscenza_lingue?: Array<Decodifica>;
    conoscenze_informatiche?: Array<TipoConoscenzaInformatica>;
    /**
     * categorie silp di massima in cui suddividere le conoscenze informatiche. Non hanno un corrispettivo ministeriale, servono solo a semplificare le ricerche
     */
    categorie_conoscenza_informatiche?: Array<Decodifica>;
    gradi_conoscenza_informatica?: Array<Decodifica>;
    patenti?: Array<Decodifica>;
    patentini?: Array<Decodifica>;
    albi?: Array<Decodifica>;
    tipi_contratto?: Array<TipoContratto>;
    categorie_inquadramento?: Array<Decodifica>;
    modalita_lavoro?: Array<Decodifica>;
    certificazioni_attestazioni?: Array<Decodifica>;
    regioni?: Array<Decodifica>;
    settori_ateco?: Array<Decodifica>;
}
