/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Sportello } from './sportello';


export interface Ente { 
    gruppo_operatore?: string;
    cod_operatore?: number;
    subcodice?: number;
    descrizione?: string;
    codice_ministeriale_comune?: string;
    codice_intermediario?: string;
    sportelli?: Array<Sportello>;
}
