/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConfigurazioneRisposta } from './configurazioneRisposta';
import { DatiProfilingDid } from './datiProfilingDid';
import { ErrorDef } from './errorDef';


/**
 * esito ricerca dettaglio Dichiarazione Immediata Disponibilita
 */
export interface EsitoDettaglioDid { 
    /**
     * id DID
     */
    id_did?: number;
    /**
     * data did
     */
    data_did?: Date;
    flg_rifiuto?: string;
    motivo_rifiuto?: string;
    flg_ente_titolarita_piemontese?: string;
    ente_titolarita?: string;
    flg_rapporto_lavoro_aperto?: string;
    flg_percettore?: string;
    flg_rapporto_lavoro_chiuso?: string;
    /**
     * codice ultimo stato
     */
    cod_ultimo_stato?: string;
    flg_stato_finale?: string;
    /**
     * S conferito , null o N non conferito
     */
    flg_attesa_invio?: string;
    /**
     * data ultimo stato
     */
    data_stato?: Date;
    /**
     * data did respinta
     */
    data_did_respinta?: Date;
    dati_profiling_did?: DatiProfilingDid;
    errore_ricerca_did?: ErrorDef;
    contenuto?: Array<ConfigurazioneRisposta>;
    error?: Array<string>;
    info?: Array<string>;
    warning?: Array<string>;
}
