/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DatoreLavoro } from './datoreLavoro';
import { Decodifica } from './decodifica';
import { Indirizzo } from './indirizzo';


export interface EsperienzaLavoro { 
    data_inizio_rapporto?: Date;
    data_fine_rapporto?: Date;
    tipo_contratto?: Decodifica;
    qualifica?: Decodifica;
    categoria_inquadramento?: Decodifica;
    datore_lavoro?: DatoreLavoro;
    azienda_utilizzatrice?: DatoreLavoro;
    data_fine_periodo_formativo?: Date;
    principali_mansioni?: string;
    assunzione_l68?: boolean;
    lavoratore_in_mobilita?: boolean;
    lavoro_stagionale?: boolean;
    lavoro_in_agricoltura?: boolean;
    /**
     * indica che l'esperienza e' dichiarata dal cittadino, non proveniente da una comunicazione ufficiale, puo' quindi essere modificata
     */
    esperienza_dichiarata?: boolean;
    modalita_lavoro?: Decodifica;
    indirizzo_di_lavoro?: Indirizzo;
}
