/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface InformazioneAggiuntiva { 
    codice?: number;
    codice_configurazione?: number;
    descrizione_configurazione?: string;
    data?: Date;
    valore?: string;
    note?: string;
}
