/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Decodifica } from './decodifica';


export interface IscrizioneCollocamentoMirato { 
    idIscrizione?: number;
    dataIscrizione?: Date;
    dataAnzianita?: Date;
    numeroIscrizione?: string;
    provincia?: Decodifica;
    cpi?: Decodifica;
    idCpiSilp?: number;
    categoria?: string;
    gradoInvalidita?: string;
    percentualeInvalidita?: string;
    dataStato?: Date;
    stato?: Decodifica;
    statoFinale?: boolean;
    note?: string;
}
