/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Provincia } from './provincia';


export interface ListaSpeciale { 
    tipo_lista?: number;
    descrizione_lista?: string;
    data_iscrizione_lista?: Date;
    data_termine_iscrizione?: Date;
    data_massimo_differimento?: Date;
    provincia?: Provincia;
}
