/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface MenuHomeCard { 
    id_card?: string;
    titolo?: string;
    testo?: string;
    url_img?: string;
    icon?: string;
    link?: string;
    tipo_link?: string;
    cod_app?: string;
    flg_accesso_autenticato?: boolean;
}
