/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ParametriDuplicazioneCalendario { 
    nome_calendario?: string;
    ambito?: string;
    gruppo_operatore?: string;
    codice_operatore?: number;
    subcodice?: number;
    duplica_fasce?: boolean;
    duplica_eccezioni?: boolean;
}
