/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ParametriSalvataggioIncontro { 
    id_prenotazione?: number;
    id_prenotazione_old?: number;
    id_utente?: number;
    id_slot?: number;
    id_stato_appuntamento?: string;
    id_sil_rif_ambito?: number;
    note?: string;
}
