/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ParametriRicercaCalendari { 
    cod_ambito?: string;
    gruppo_operatore?: string;
    cod_operaratore?: number;
    subcodice?: number;
    data_da?: Date;
    data_a?: Date;
    nome_calendario?: string;
    calendario_eliminato?: boolean;
    /**
     * tipologia di utente CIT, APL, CPI, REG
     */
    cod_tipo_utente?: string;
    /**
     * se valorizzato include nel risultato solo i calendari per cui questa eccezione sia valorizzabile
     */
    id_eccezione_applicabile?: number;
}
