/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PermessoDiSoggiorno { 
    titolo?: string;
    numero?: string;
    data_scadenza?: Date;
    motivo_rilascio?: string;
    codice_ministeriale_motivo_rilascio?: string;
    codice_ministeriale_status_extra_ue?: string;
}
