/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Decodifica } from './decodifica';
import { EventoPolitica } from './eventoPolitica';


export interface PoliticaAttiva { 
    /**
     * tabella ministeriale TIPO ATTIVITA es. A02 PATTO DI ATTIVAZIONE ED EVENTUALE PROFILING
     */
    attivita?: Decodifica;
    denominazione?: string;
    data_proposta?: string;
    data_inizio?: string;
    data_fine?: string;
    durata?: number;
    /**
     * O ore, G giorni, M mesi, A anni
     */
    tipo_durata?: string;
    descrizione?: string;
    /**
     * tabella ministeriale TIPO PROGETTI es. 02 GARANZIA GIOVANI
     */
    titolo_progetto?: Decodifica;
    /**
     * tabella ministeriale CPI, rappresenta CPI o Societa' che ha fornito la politica
     */
    ente_promotore?: Decodifica;
    identificativo_politica?: string;
    identificativo_presa_in_carico?: string;
    /**
     * numero decimale di lunghezza totale 10 con 9 decimali. Rappresento in stringa per comodita
     */
    indice_profiling?: string;
    ultimo_evento?: EventoPolitica;
}
