/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SlotIncontro } from './slotIncontro';
import { Sportello } from './sportello';


export interface PrenotazioneIncontro { 
    id_prenotazione?: number;
    cod_ambito?: string;
    codice_anpal_stato_incontro?: string;
    sportello?: Sportello;
    slot?: SlotIncontro;
}
