/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CondizioneOccupazionale } from './condizioneOccupazionale';
import { MotivoPresenzaInItalia } from './motivoPresenzaInItalia';
import { TitoloStudio } from './titoloStudio';


export interface ProfilingYG { 
    indice?: number;
    descrizione_indice?: string;
    data_profiling?: Date;
    eta?: number;
    genere?: string;
    titolo_studio?: TitoloStudio;
    condizione_occupazionale?: CondizioneOccupazionale;
    motivo_presenza_in_italia?: MotivoPresenzaInItalia;
    codice_ministeriale_provincia?: string;
}
