/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ReferenteServizioTerritoriale { 
    cognome_referente?: string;
    nome_referente?: string;
    ente_referente?: string;
    email_referente?: string;
    telefono_referente?: string;
    cellulare_referente?: string;
}
