/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Responsabile { 
    /**
     * id responsabile==id utente
     */
    id_responsabile?: number;
    /**
     * nazione di residenza
     */
    idSilTNazioneRes?: string;
    /**
     * indirizzo di domicilio
     */
    dsIndirizzoDom?: string;
    /**
     * fax
     */
    dsFax?: string;
    /**
     * numero civico domicilio
     */
    dsNumCivicoDom?: string;
    /**
     * comune di domicilio
     */
    idSilTComuneDom?: string;
    /**
     * genere
     */
    genere?: string;
    /**
     * cap comune domicilio
     */
    capDom?: string;
    /**
     * indirizzo di residenza
     */
    dsIndirizzoRes?: string;
    /**
     * comune di residenza
     */
    idSilTComuneRes?: string;
    /**
     * data scadenza permesso di soggiorno
     */
    dScadenzaPermSogg?: Date;
    /**
     * citadinanza
     */
    idSilTCittadinanza?: string;
    /**
     * provincia di domicilio
     */
    idSilTProvinciaDom?: string;
    /**
     * toponimo di domicilio
     */
    idSilTToponimoDom?: string;
    /**
     * provincia di residenza
     */
    idSilTProvinciaRes?: string;
    /**
     * data di nascita
     */
    dNascita?: Date;
    /**
     * telefono cellulare
     */
    dsTelefonoCellulare?: string;
    /**
     * indirizzo di residenza esteso
     */
    dsIndirizzoResEsteso?: string;
    /**
     * comune di nascita
     */
    idSilTComuneNasc?: string;
    /**
     * numero permesso di soggiorno
     */
    numeroPermSogg?: string;
    /**
     * nazione di nascita
     */
    idSilTNazioneNasc?: string;
    /**
     * cap comune di residenza
     */
    capRes?: string;
    /**
     * telefono fisso
     */
    dsTelefonoFisso?: string;
    /**
     * numero civico di residenza
     */
    dsNumCivicoRes?: string;
    /**
     * status lavoratore extra UE
     */
    idSilTStatusLavExtraUe?: string;
    /**
     * motivo rilascio permesso di soggiorno
     */
    idSilTMotRilPerm?: string;
    /**
     * toponimo di residenza
     */
    idSilTToponimoRes?: string;
    /**
     * indirizzo di domicilio esteso
     */
    dsIndirizzoDomEsteso?: string;
    /**
     * nazione di domicilio
     */
    idSilTNazioneDom?: string;
}
