/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface RichiestaIscrizioneL68Header { 
    /**
     * id richiesta
     */
    id_richiesta?: number;
    /**
     * id richiesta
     */
    id_anagrafica?: number;
    /**
     * B = Bozza - I = Inviato - A = Accettata - R = Rifiutata - O = Annullato da Operatore
     */
    cod_stato_richiesta?: string;
    /**
     * data stato richiesta
     */
    data_stato?: Date;
    /**
     * codice fiscale utente
     */
    codice_fiscale?: string;
    cognome?: string;
    nome?: string;
    descr_provincia?: string;
    descr_tipo_iscrizione?: string;
    descr_tipo_comunicazione?: string;
    descr_stato_richiesta_iscrizione?: string;
    descr_cpi?: string;
    descr_cpi_ultima_iscrizione?: string;
    flg_presa_in_carico?: string;
    descr_operatore_presa_in_carico?: string;
    descr_motivo_richiesta?: string;
    descr_categoria_invalidita?: string;
    /**
     * codice fiscale operatore
     */
    codice_fiscale_operatore?: string;
    cognome_operatore?: string;
    nome_operatore?: string;
}
