/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface RispostaQuestionario { 
    id_domanda?: number;
    id_risposta?: number;
    id_configurazione_questionario?: number;
    risposta_libera?: string;
}
