/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConoscenzaInformatica } from './conoscenzaInformatica';
import { DatiAmministrativi } from './datiAmministrativi';
import { Decodifica } from './decodifica';
import { Esito } from './esito';
import { EsperienzaLavoro } from './esperienzaLavoro';
import { FormazioneProfessionale } from './formazioneProfessionale';
import { Indirizzo } from './indirizzo';
import { Lingua } from './lingua';
import { Luogo } from './luogo';
import { PermessoDiSoggiorno } from './permessoDiSoggiorno';
import { PoliticaAttiva } from './politicaAttiva';
import { Recapito } from './recapito';
import { TitoloDiStudio } from './titoloDiStudio';


export interface SchedaAnagraficoProfessionale { 
    identificativo_sap?: string;
    /**
     * id lavoratore su SILP
     */
    id_sil_lav_anagrafica?: number;
    /**
     * id del record di interscambio che traccia una sap ricevuta e importata da silp
     */
    id_interscambio_sap?: number;
    /**
     * data in cui e' avvenuto l'ultimo aggiornamento di un dato della sap
     */
    data_ultimo_aggiornamento?: Date;
    ente_titolare?: Decodifica;
    /**
     * codice fiscale utente
     */
    codice_fiscale?: string;
    nome?: string;
    cognome?: string;
    sesso?: string;
    dataDiNascita?: Date;
    luogoDiNascita?: Luogo;
    cittadinanza?: string;
    codice_ministeriale_cittadinanza?: string;
    residenza?: Indirizzo;
    domicilio?: Indirizzo;
    recapito?: Recapito;
    permessoDiSoggiorno?: PermessoDiSoggiorno;
    datiAmministrativi?: DatiAmministrativi;
    esperienze_di_lavoro?: Array<EsperienzaLavoro>;
    titoli_di_studio?: Array<TitoloDiStudio>;
    formazione_professionale_corsi?: Array<FormazioneProfessionale>;
    lingue_straniere?: Array<Lingua>;
    conoscenze_informatiche?: Array<ConoscenzaInformatica>;
    albi?: Array<Decodifica>;
    patenti?: Array<Decodifica>;
    patentini?: Array<Decodifica>;
    politiche_attive?: Array<PoliticaAttiva>;
    /**
     * esito valorizzato in caso di problemi logici nel caricamento sap, esempio codice sap duplicato
     */
    esito?: Esito;
}
