/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Widget } from './widget';


/**
 * informazioni strutturali di una schermata, con abilitazioni
 */
export interface Screen { 
    /**
     * codice univoco dell'elemento
     */
    cod?: string;
    /**
     * elenco dei widget della schermata, con abilitazioni
     */
    widgets?: Array<Widget>;
}
