/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Sportello { 
    gruppo_operatore?: string;
    cod_operatore?: number;
    subcodice?: number;
    codice_ministeriale_comune?: string;
    codice_intermediario?: string;
    descrizione?: string;
    descrizione_indirizzo?: string;
    gruppo_operatore_ente_appartenenza?: string;
    cod_operatore_ente_appartenenza?: number;
    subcodice_ente_appartenenza?: number;
}
