/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface StatusExtraUE { 
    /**
     * codice ministeriale
     */
    codice_ministeriale?: string;
    /**
     * descrizione
     */
    descrizione?: string;
    /**
     * id tipo documento soggiorno
     */
    id_tipo_documento_soggiorno?: string;
    /**
     * data inizio
     */
    data_inizio?: Date;
    /**
     * data fine
     */
    data_fine?: Date;
}
