/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TipoConoscenzaInformatica { 
    codice_ministeriale?: string;
    codice_silp?: string;
    descrizione?: string;
    data_inizio_validita?: Date;
    data_fine_validita?: Date;
    codice_categoria_conoscenza_informatica?: string;
}
