/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GradoStudio } from './gradoStudio';


export interface TitoloStudio { 
    codice?: string;
    codice_silp?: string;
    descrizione?: string;
    descrizioneTipoScuola?: string;
    sinonimo?: string;
    gradoStudio?: GradoStudio;
}
