/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Decodifica } from './decodifica';
import { GradoStudio } from './gradoStudio';
import { Luogo } from './luogo';


export interface TitoloDiStudio { 
    /**
     * da tabella ministeriale LIVELLO DI STUDIO, 2 caratteri es. 20 SCUOLA MEDIA
     */
    livello_scolarizzazione?: GradoStudio;
    /**
     * da tabella ministeriale TDS completa con indici, 8 caratteri  es. 30101005  Esperto agrumicoltore
     */
    corso_di_studio?: Decodifica;
    descrizione?: string;
    frequentato_in?: Luogo;
    riconosciuto_in_italia?: boolean;
    anno_se_conseguito?: number;
    votazione_conseguita?: string;
    ultimo_anno_frequentato_se_non_conseguito?: number;
    anno_di_frequenza_se_in_corso?: number;
}
