/**
 * Portale Servizi Lavoro API
 * API per il backend del portale servizi lavoro.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UtentePresaVisione } from './utentePresaVisione';


export interface Utente { 
    /**
     * id utente su PSL
     */
    id_utente?: number;
    /**
     * id lavoratore su SILP
     */
    id_sil_lav_anagrafica?: number;
    identificativoSap?: string;
    /**
     * codice tipo utente definito nella tabella PSLP_D_TIPO_UTENTE (APL, CIT, CPI)
     */
    codice_tipo_utente?: string;
    /**
     * codice fiscale utente
     */
    codice_fiscale?: string;
    nome?: string;
    cognome?: string;
    email?: string;
    prese_visione?: Array<UtentePresaVisione>;
}
