/**
 * Sezioni SAP
 */
export enum SezioniSAP {
  DATI_ANAGRAFICI = 'DATI_ANAGRAFICI',
  DATI_AMMINISTRATIVI = 'DATI_AMMINISTRATIVI',
  ESPERIENZE_LAVORO = 'ESPERIENZE_LAVORO',
  ISTRUZIONE = 'ISTRUZIONE',
  FORMAZIONE_PROFESSIONALE = 'FORMAZIONE_PROFESSIONALE',
  LINGUE_STRANIERE = 'LINGUE_STRANIERE',
  CONOSCENZE_INFORMATICHE = 'CONOSCENZE_INFORMATICHE',
  ABILITAZIONI_E_PATENTI = 'ABILITAZIONI_E_PATENTI',
  POLITICHE_ATTIVE = 'POLITICHE_ATTIVE'
}


/**
 * Modifiche SAP
 */
export interface ModificheSAP {
  elencoModifiche: { key: string, value: boolean }[];
  sapModificata: boolean;
}
